define(['handlebars'], function(Handlebars) {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['db_model'] = template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Handlebars.helpers); data = data || {};
  var buffer = "", stack1, functionType="function", escapeExpression=this.escapeExpression;


  buffer += "                    <div class=\"row-fluid\">\r\n                          <div class=\"navbar\">\r\n                              <div class=\"navbar-inner\">\r\n                                  <ul class=\"breadcrumb\">\r\n                                      <i class=\"icon-chevron-left hide-sidebar\"><a href=\"#\" title=\"Hide Sidebar\" rel=\"tooltip\">&nbsp;</a></i>\r\n                                      <i class=\"icon-chevron-right show-sidebar\" style=\"display:none;\"><a href=\"#\" title=\"Show Sidebar\" rel=\"tooltip\">&nbsp;</a></i>\r\n                                      <li>\r\n                                          <a href=\"#\">Dashboard</a> <span class=\"divider\">/</span>  \r\n                                      </li>\r\n                                      <li>\r\n                                          <a href=\"#\">Settings</a> <span class=\"divider\">/</span> \r\n                                      </li>\r\n                                      <li class=\"active\">Tools</li>\r\n                                  </ul>\r\n                              </div>\r\n                          </div>\r\n                      </div>\r\n\r\n                    <!-- morris stacked chart -->\r\n                    <div id=\"db_model_detail\" class=\"row-fluid\" style=\"display:none;\">\r\n                        <!-- block -->\r\n                        <div class=\"block\">\r\n                            <div class=\"navbar navbar-inner block-header\">\r\n                                <div class=\"muted pull-left\">";
  if (stack1 = helpers.nav_title) { stack1 = stack1.call(depth0, {hash:{},data:data}); }
  else { stack1 = depth0.nav_title; stack1 = typeof stack1 === functionType ? stack1.apply(depth0) : stack1; }
  buffer += escapeExpression(stack1)
    + "</div>\r\n                            </div>\r\n                            <div class=\"block-content collapse in\">\r\n                                <div class=\"span12\">\r\n                                     <form class=\"form-horizontal\" method=\"post\" action=\"/bmw/app/api/v1/db_model.php/add_table\">\r\n                                      <input name=\"rid\" id=\"rid\" type=\"hidden\" value=\"";
  if (stack1 = helpers.rid) { stack1 = stack1.call(depth0, {hash:{},data:data}); }
  else { stack1 = depth0.rid; stack1 = typeof stack1 === functionType ? stack1.apply(depth0) : stack1; }
  buffer += escapeExpression(stack1)
    + "\" />\r\n                                      <fieldset>\r\n                                        <legend>建立/修改数据表</legend>\r\n                                        <div class=\"control-group\">\r\n                                          <label class=\"control-label\" for=\"tbname\">数据表名</label>\r\n                                          <div class=\"controls\">\r\n                                            tbl_model_<input class=\"input-medium\" name=\"tbname\" id=\"tbname\" type=\"text\" value=\"";
  if (stack1 = helpers.tbname) { stack1 = stack1.call(depth0, {hash:{},data:data}); }
  else { stack1 = depth0.tbname; stack1 = typeof stack1 === functionType ? stack1.apply(depth0) : stack1; }
  buffer += escapeExpression(stack1)
    + "\">\r\n                                            <span class=\"help-inline\">*(如:news,只能由字母、数字组成)</span>\r\n                                          </div>\r\n                                        </div>\r\n                                        <div class=\"control-group\">\r\n                                          <label class=\"control-label\" for=\"tname\">数据表标识</label>\r\n                                          <div class=\"controls\">\r\n                                            <input class=\"input-large\" name=\"tname\" id=\"tname\" type=\"text\" value=\"";
  if (stack1 = helpers.tname) { stack1 = stack1.call(depth0, {hash:{},data:data}); }
  else { stack1 = depth0.tname; stack1 = typeof stack1 === functionType ? stack1.apply(depth0) : stack1; }
  buffer += escapeExpression(stack1)
    + "\" />\r\n                                            <span class=\"help-inline\">*(如:新闻数据表)</span>\r\n                                          </div>\r\n                                        </div>\r\n                                        <div class=\"control-group\">\r\n                                          <label class=\"control-label\" for=\"tsay\">备注</label>\r\n                                          <div class=\"controls\">\r\n                                            <textarea class=\"input-xlarge textarea\" id=\"tsay\" name=\"tsay\" style=\"width: 300px; height: 100px\">";
  if (stack1 = helpers.tsay) { stack1 = stack1.call(depth0, {hash:{},data:data}); }
  else { stack1 = depth0.tsay; stack1 = typeof stack1 === functionType ? stack1.apply(depth0) : stack1; }
  buffer += escapeExpression(stack1)
    + "</textarea>\r\n                                          </div>\r\n                                        </div>                                \r\n                                        <div class=\"form-actions\">\r\n                                          <button type=\"submit\" class=\"btn btn-primary\">提交</button>\r\n                                          <button type=\"reset\" class=\"btn\">重置</button>\r\n                                        </div>\r\n                                      </fieldset>\r\n                                    </form>\r\n\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <!-- /block -->\r\n                    </div>\r\n\r\n\r\n					<!-- morris stacked chart -->\r\n                    <div id=\"db_model_list\" class=\"row-fluid\">\r\n                        <!-- block -->\r\n                        <div class=\"block\">\r\n                            <div class=\"navbar navbar-inner block-header\">\r\n                                <div class=\"muted pull-left\">Bootstrap dataTables</div>\r\n                            </div>\r\n                            <div class=\"block-content collapse in\">                             \r\n                                <div class=\"span12 well\">\r\n                                    <span id=\"act_add\" class=\"btn\">添加</span>\r\n                                </div>\r\n                            </div>\r\n                            <div class=\"block-content collapse in\">                             \r\n                                <div class=\"span12\" id=\"table_container\">\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <!-- /block -->\r\n                    </div>";
  return buffer;
  });
return templates;
});